apiVersion: v1
kind: Pod
metadata:
  name: jetty-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: sample-jetty-app
    image: hashmapinc/sample_app:latest
    ports:
    - containerPort: 8080
    - hostPort: 8080