apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: jetty-pod
  labels:
    app: jetty-pod
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: jetty-pod
        tier: frontend
    spec:
      containers:
      - name: sample-jetty-app
        image: hashmapinc/sample_app:latest
        ports:
        - containerPort: 8080
