apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-jetty-test
spec:
  replicas: 3
  selector:
    app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: hashmapinc/sample_app:latest
        ports:
        - containerPort: 8080